version: "3.8"

volumes: # Note these will be prefixed by affinda_ when created by docker compose
  pgdata_selfhosted:
  affinda_shared:

services:
  # Local dev containers
  text_extraction:
    image: affinda/text_extraction:latest
    ports:
      - "${TEXT_EXTRACTION_PORT:-5010}:${TEXT_EXTRACTION_PORT:-5010}"
    environment:
      SENTRY_ENABLED: "0"
      TEXT_EXTRACTION_PORT: "${TEXT_EXTRACTION_PORT:-5010}"
      SENTRY_DSN_TYPE: "${SENTRY_DSN_TYPE:-DEV}"

  ocr:
    image: affinda/ocr:latest
    ports:
      - "${OCR_PORT:-5011}:${OCR_PORT:-5011}"
    environment:
      SENTRY_ENABLED: "0"
      OCR_PORT: "${OCR_PORT:-5011}"
      SENTRY_DSN_TYPE: "${SENTRY_DSN_TYPE:-DEV}"


  pdfkit:
    image: affinda/pdfkit:latest
    ports:
      - "${PDFKIT_PORT:-5012}:${PDFKIT_PORT:-5012}"
    environment:
      SENTRY_ENABLED: "0"
      PDFKIT_PORT: "${PDFKIT_PORT:-5012}"
      SENTRY_DSN_TYPE: "${SENTRY_DSN_TYPE:-DEV}"

  libre_office:
    image: affinda/libre_office:latest
    hostname: libreoffice
    ports:
      - "${LIBRE_OFFICE_PORT:-5013}:${LIBRE_OFFICE_PORT:-5013}"
    environment:
      LIBRE_OFFICE_PORT: "${LIBRE_OFFICE_PORT:-5013}"


  inference:
    image: affinda/affinda-inference-selfhosted-resumes:latest
    ports:
      - "${TORCHSERVE_INFERENCE_PORT:-5014}:${TORCHSERVE_INFERENCE_PORT:-5014}"
      - "${TORCHSERVE_MANAGEMENT_PORT:-5015}:${TORCHSERVE_MANAGEMENT_PORT:-5015}"
    environment:
      TS_INFERENCE_ADDRESS: "http://0.0.0.0:${TORCHSERVE_INFERENCE_PORT:-5014}"
      TS_MANAGEMENT_ADDRESS: "http://0.0.0.0:${TORCHSERVE_MANAGEMENT_PORT:-5015}"
      SENTRY_ENABLED: "0"
      SENTRY_DSN_TYPE: "${SENTRY_DSN_TYPE:-DEV}"
      TS_MODEL_CONFIG: >-  # Won't append newlines or add newlines in string
        {
        "headshot":{"1.0":{"defaultVersion":true,"minWorkers":1,"maxWorkers":1}},
        "resumes_layout_tagger_mt":{"1.0":{"defaultVersion":true,"minWorkers":1,"maxWorkers":1}},
        "resumes_layout_tagger_mt_xlm":{"1.0":{"defaultVersion":true,"minWorkers":1,"maxWorkers":1}}
        }
    healthcheck:
      test: "curl --fail http://0.0.0.0:${TORCHSERVE_INFERENCE_PORT:-5014}/ping || exit 1"
      interval: 5s
      timeout: 2s
      start_period: 20s
      retries: 20
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu, utility, compute ]

  db:
    image: affinda/affinda-db:latest
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: affinda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: "${DB_PORT:-5432}"
    command:
      - "-p ${DB_PORT:-5432}"
    healthcheck:
      test: "pg_isready -q -d affinda -U postgres --port ${DB_PORT:-5432}"
      interval: 2s
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
      - pgdata_selfhosted:/var/lib/postgresql/data


  redis:
    image: affinda/affinda-redis:latest
    healthcheck:
      test: "redis-cli -p 6379 ping"
      interval: 2s
    ports:
      - "6379:6379"
    volumes:
      - affinda_shared:/opt/shared/

  # APPS Services
  web:
    image: affinda/affinda-selfhosted:latest
    restart: always
    ports:
      - "${HOST_PORT:-80}:80"
    environment:
      APPS_MODE: "WEB_SELFHOSTED"
      SENTRY_ENABLED: "0"
      SENTRY_DSN_TYPE: "${SENTRY_DSN_TYPE:-DEV}"
      DJANGO_SECRET_KEY: "5TS1pUeIwzdPlpPunaEGiMyznTPWEH0nwwMHNg78kSb111BlqK9Juh123456789X"
      DJANGO_SETTINGS_MODULE: "config.settings.selfhosted"
      DJANGO_SUPERUSER_PASSWORD: "changeme"
      API_ROOT_URL: "http://api.localhost:80"
      HOME: "/opt/affinda"
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      PYTHONUNBUFFERED: "1"
      SENTRY_ENVIRONMENT: "selfhosted"
      # DOCKER specific ENV VARS defaults are in config.settings.base
      TEXT_EXTRACTION_PORT: "${TEXT_EXTRACTION_PORT:-5010}"
      OCR_PORT: "${OCR_PORT:-5011}"
      PDFKIT_PORT: "${PDFKIT_PORT:-5012}"
      LIBRE_OFFICE_PORT: "${LIBRE_OFFICE_PORT:-5013}"
      TORCHSERVE_INFERENCE_PORT: "${TORCHSERVE_INFERENCE_PORT:-5014}"
      TORCHSERVE_MANAGEMENT_PORT: "${TORCHSERVE_MANAGEMENT_PORT:-5015}"
      DB_PORT: "${DB_PORT:-5432}"
      REDIS_PORT: "6379"
      USE_ELASTICSEARCH: "0"
    healthcheck:
      test: "curl --fail http://localhost:80/admin || exit 1"
      interval: 5s
      timeout: 3s
      start_period: 600s
      retries: 20

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - affinda_shared:/opt/shared/

  celery_worker:
    image: affinda/affinda-selfhosted:latest
    environment:
      APPS_MODE: "CELERY_WORKER"
      SENTRY_ENABLED: "0"
      SENTRY_DSN_TYPE: "${SENTRY_DSN_TYPE:-DEV}"
      DJANGO_SECRET_KEY: "5TS1pUeIwzdPlpPunaEGiMyznTPWEH0nwwMHNg78kSb111BlqK9Juh123456789X"
      DJANGO_SETTINGS_MODULE: "config.settings.selfhosted"
      DJANGO_SUPERUSER_PASSWORD: "changeme"
      HOME: "/opt/affinda"
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      PYTHONUNBUFFERED: "1"
      SENTRY_ENVIRONMENT: "selfhosted"
      # GPU specific params
      PRELOAD_SMALL_MODELS: "True"
      C_FORCE_ROOT: "1"
      CELERY_QUEUES: "priority_1,priority_2,priority_3,priority_4"
      CELERY_DEBUG_LEVEL: "INFO"
      # DOCKER specific ENV VARS defaults are in config.settings.base
      TEXT_EXTRACTION_PORT: "${TEXT_EXTRACTION_PORT:-5010}"
      OCR_PORT: "${OCR_PORT:-5011}"
      PDFKIT_PORT: "${PDFKIT_PORT:-5012}"
      LIBRE_OFFICE_PORT: "${LIBRE_OFFICE_PORT:-5013}"
      TORCHSERVE_INFERENCE_PORT: "${TORCHSERVE_INFERENCE_PORT:-5014}"
      TORCHSERVE_MANAGEMENT_PORT: "${TORCHSERVE_MANAGEMENT_PORT:-5015}"
      DB_PORT: "${DB_PORT:-5432}"
      REDIS_PORT: "6379"
      USE_ELASTICSEARCH: "0"
    deploy:
      replicas: 2

    volumes:
      - affinda_shared:/opt/shared/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_healthy
      ocr:
        condition: service_healthy
      text_extraction:
        condition: service_healthy
      pdfkit:
        condition: service_healthy
      libre_office:
        condition: service_healthy
      inference:
        condition: service_healthy

  celery_beat:
    image: affinda/affinda-selfhosted:latest
    environment:
      APPS_MODE: "CELERY_BEAT"
      SENTRY_ENABLED: "0"
      SENTRY_DSN_TYPE: "${SENTRY_DSN_TYPE:-DEV}"
      DJANGO_SECRET_KEY: "5TS1pUeIwzdPlpPunaEGiMyznTPWEH0nwwMHNg78kSb111BlqK9Juh123456789X"
      DJANGO_SETTINGS_MODULE: "config.settings.selfhosted"
      DJANGO_SUPERUSER_PASSWORD: "changeme"
      HOME: "/opt/affinda"
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      PYTHONUNBUFFERED: "1"
      # GPU specific params
      PRELOAD_SMALL_MODELS: "False"
      C_FORCE_ROOT: "1"
      CELERY_QUEUES: "priority_1,priority_2,priority_3,priority_4"
      CELERY_DEBUG_LEVEL: "INFO"
      SENTRY_ENVIRONMENT: "selfhosted"
      # DOCKER specific ENV VARS defaults are in config.settings.base
      TEXT_EXTRACTION_PORT: "${TEXT_EXTRACTION_PORT:-5010}"
      OCR_PORT: "${OCR_PORT:-5011}"
      PDFKIT_PORT: "${PDFKIT_PORT:-5012}"
      LIBRE_OFFICE_PORT: "${LIBRE_OFFICE_PORT:-5013}"
      TORCHSERVE_INFERENCE_PORT: "${TORCHSERVE_INFERENCE_PORT:-5014}"
      TORCHSERVE_MANAGEMENT_PORT: "${TORCHSERVE_MANAGEMENT_PORT:-5015}"
      DB_PORT: "${DB_PORT:-5432}"
      REDIS_PORT: "6379"
      USE_ELASTICSEARCH: "0"

    deploy:
      replicas: 1

    volumes:
      - affinda_shared:/opt/shared/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_healthy
      ocr:
        condition: service_healthy
      text_extraction:
        condition: service_healthy
      pdfkit:
        condition: service_healthy
      libre_office:
        condition: service_healthy
      inference:
        condition: service_healthy
